package com.mmfsin.copixuelas.quepreferirias

object MainData {

    fun getDilemmas(): List<String> {
        val dilemmas = mutableListOf<String>()
        dilemmas.add("Que yo no me juro %OR% te lo drogo")
        dilemmas.add("No poder usar ningún medio de transporte nunca más o perder una pierna ")
        dilemmas.add("Quedarte sin familia o quedarte sin amigos ")
        dilemmas.add("Hacerte rico y famoso por grabar un video porno o ganar un premio Nobel y que nadie se entere nunca ")
        dilemmas.add("Ser virgen hasta los 40 o no poder follar a partir de los 40 ")
        dilemmas.add("Tirarte a tu madre o padre y que nadie lo sepa nunca o no hacerlo y que todo el mundo piense que lo has hecho ")
        dilemmas.add("Liarte con la persona de tu derecha o de tu izquierda. Al que no elijas, bebe ")
        dilemmas.add("Matar a alguien que no conoces por diez millones de euros o no matar a nadie ")
        dilemmas.add("Que tus polvos duren siempre 5 minutos o 5 horas ")
        dilemmas.add("Saber la fecha de tu muerte y vivir hasta ese día, o no saberlo y reducir el tiempo que te quede de vida a la mitad ")
        dilemmas.add("Ver el principio de la humanidad o conocer cómo será el final de todo ")
        dilemmas.add("Hablar muchos idiomas pero no viajar nunca o solo hablar un idioma y viajar mucho ")
        dilemmas.add("Hacer canibalismo con los cadáveres de tus amigos o morir de hambre")
        dilemmas.add("No poder volver a escuchar música nunca más o no poder volver a usar internet ")
        dilemmas.add("No tener pulgares o no tener dedos índice ")
        dilemmas.add("Quedarte sin dientes o quedarte sin lengua ")
        dilemmas.add("Estar enamorado/a de tu pareja pero no poder follar nunca o estar en una relación tóxica con un sexo increíble ")
        dilemmas.add("Vivir eternamente o morir a los 50")
        dilemmas.add("Sacrificarte para salvar a tu pareja o sacrificarte para salvar a tu mejor amigo")
        dilemmas.add("Sacrificarte por salvar la humanidad, o no y a tomar por culo todo el mundo")
        dilemmas.add("Padres eternos o mascotas eternas ")
        dilemmas.add("Poner los cuernos o que te los pongan")
        dilemmas.add("Ser horriblemente feo/a pero muy bueno en la cama, o increíblemente guapo/a y malísimo en el sexo ")
        dilemmas.add("Perder un ojo o perder una mano")
        dilemmas.add("No poder volver a ver una película o no poder volver a ver una serie ")
        dilemmas.add("Tener que escuchar la misma canción una vez al día el resto de tu vida o solo comer verduras el resto de tu vida")
        dilemmas.add("Acabar con la todas las guerras o acabar con el hambre en el mundo ")
        dilemmas.add("Que te paguen por estudiar o que nunca más te cueste encontrar trabajo")
        dilemmas.add("Tener dinero infinito pero solo poder comprar cosas menores de 500€ (sin poder alquilar ni pagar a plazos) o quedarte como estás")
        dilemmas.add("Usar siempre solo dinero en efectivo o con tarjeta ")
        dilemmas.add("Estar muy musculado y ser horriblemente feo, o ser muy guapo y pesar 20kg")
        dilemmas.add("Poder tener todos los conociemientos que quieras y no poder contarle nada a nadie, o seguir siendo un ignorante de la vida ")
        dilemmas.add("Tener una mansión o tener un yate")
        dilemmas.add("¿A quién salvarías antes de la muerte? A un niño rico y mimado o a un cachorrito abandonado")
        dilemmas.add("Ser mundialmente conocido o ser alguien normal")
        dilemmas.add("No volver a coger un ordenador o no volver a conducir un coche ")
        dilemmas.add("Matar cien cachorritos o matar a un bebé ")
        dilemmas.add("No tener calefacción en inviarno o no tener ventilador/aire acondicionado en verano ")
        dilemmas.add("Hablar muchos idiomas o hablar con los animales ")
        dilemmas.add("No poder saborear la comida nunca más, o no volver a escuchar música ")
        dilemmas.add("Tener los dedos de las manos como tus piernas de largo, o tener tus piernas como tus dedos de largo ")
        dilemmas.add("Tener la nariz donde la boca y viceversa o tener un ojo encima del otro")
        dilemmas.add("Tener el cuello como una girafa o tener pezuñas de cerdo ")
        dilemmas.add("Tener un cuerno de rinoceronte en la frente o tener las manos super peludas (sin poder afeitarse) ")
        dilemmas.add("Hablar a tu 'yo' del pasado o hablar con tu 'yo' del futuro")
        dilemmas.add("Una ciudad submarina o una ciudad en las nubes")
        dilemmas.add("Tardar dos horas en mear cada vez que vayas al baño o no poder estar sentado más de 10 minutos nunca más")
        dilemmas.add("Andar siempre a cuatro patas o ir siempre dando saltitos ")
        dilemmas.add("Ir descalzo siempre o tener brazos de T-Rex ")
        dilemmas.add("Tener solo dos dedos en cada mano o tener la lengua que mida 1 metro ")
        dilemmas.add("Hablar siempre a gritos o siempre susurrando ")
        dilemmas.add("Que todo lo que toques se convierta en mierda o que todo lo que pienses se oiga en alto ")
        dilemmas.add("Mearte encima siempre que tengas ganas, o tardar en dormirte siempre 4h")
        dilemmas.add("Cada vez que te haga algo gracia reírte histéricamente muy alto o tirarte pedos sonoros cada vez que te enfades ")
        dilemmas.add("Siempre follar estando arriba o siempre follar estando abajo ")
        dilemmas.add("Que te dejen de hablar y no sepas por qué o dejar de hablar a alguien y no poder explicarle por qué")
        dilemmas.add("Andar siempre para atrás o no poder correr nunca más ")
        dilemmas.add("No poder nunca acabar una frase o cada vez que hables tener que mover la cabeza en círculos")
        dilemmas.add("No volver a hacer nunca nada de deporte o no poder tomar alcohol nunca más ")
        dilemmas.add("Dar un mal consejo a posta o que te den un mal consejo ")
        dilemmas.add("Comer el resto de tu vida la misma comida o solamente poder beber agua y ninguna otra bebida ")
        dilemmas.add("Estar poco abrigado con mucho frío o muy abrigado con mucho calor ")
        dilemmas.add("Llevar siempre los calcetines mojados o tener siempre toda la ropa un poco humeda ")
        dilemmas.add("Tener siempre mucho sueño o tener siempre mucho hambre ")
        dilemmas.add("Que te duelan los ojos al cerrarlos o que te duelan los dedos cada vez que los dobles ")
        dilemmas.add("Ser el peor de lo mejor o lo mejor de lo peor")
        dilemmas.add("Poder ser invisible o que todo tu cuerpo sea elástico ")
        dilemmas.add("Follar con la persona de tus sueños una vez al año, o con alguien normal todas las veces que quieras ")
        dilemmas.add("Hacer sexo oral o que te lo hagan ")
        dilemmas.add("Tener que comer con cuchara lo que comes con tenedor o usar siempre un cuchillo de plástico ")
        dilemmas.add("Llevar siempre un pañal por encima del pantalón o llevar siempre puestas unas gafas de bucear ")
        dilemmas.add("No poder hablar cuando estés sentado o tener que tocarte las rodillas por cada paso que des la andar ")
        dilemmas.add("Ir con los brazos levantados cada vez que andes o siempre que estés sentado tener las piernas levantadas ")
        dilemmas.add("Siempre follar haciendo el misionero o siempre  follar a 4 ")
        dilemmas.add("Llevar siempre un gorro de piscina puesto o un casco de bicicleta ")
        dilemmas.add("No poder volver a masturbarte o durar siempre 10 mins follando")
        dilemmas.add("Quedarte en tu pais por siempre con muchos buenos amigos, o viajar mucho pero no tener amigos ")
        dilemmas.add("Que te pese 80kg la cabeza o que todos tus movimientos sean siempre a cámara lenta ")
        dilemmas.add("Que tu pareja mastique siempre con la boca abierta o que ronque mucho al dormir ")
        dilemmas.add("Tener un novio/a de ideología política contraria o morir solo ")
        dilemmas.add("Estar con tu pareja 20h al día o veros una vez al mes ")
        dilemmas.add("Poder resucitar a quién tu quieras o poder matar a la gente legalmente ")
        dilemmas.add("Que apruebe toda la clase menos tú o aprobar tú y todo el mundo suspende ")
        dilemmas.add("Eternos 40 grados o eternos -10 grados ")
        dilemmas.add("Ser un músico mundialmente famoso y querido o ser el descubridor de una teoría científica que revolucione el mundo ")
        dilemmas.add("Nunca cansarte o nunca enfermar ")
        dilemmas.add("Ser muy bueno cocinando o ser muy bueno arreglando y montando cosas ")
        dilemmas.add("Tú mejor amigo comete un crimen y te culpan a ti, vas a la cárcel 5 años en su lugar, o le delatas y que vaya él")
        dilemmas.add("Hacer algo increíble y que nadie lo aprecie nunca, o llevarte todo el mérito de algo que no has hecho tú ")
        dilemmas.add("Poder teletransportarte pero siempre aparecer 1 semana en el futuro o 1 semana en el pasado")
        dilemmas.add("Medir medio metro más o medio metro menos ")
        dilemmas.add("Que te mientan por tu bien, o que te digan la dolorosa verdad ")
        dilemmas.add("Ser un músico famoso o un actor famoso ")
        dilemmas.add("No tener cuello o tener los brazos la mitad de largos ")
        dilemmas.add("Tener cuatro brazos o poder dar saltos de 10 metros ")
        dilemmas.add("No necesitar dormir o no necesitar ir al baño nunca más ")
        dilemmas.add("Hacer una serie super famosa o hacer una película super famosa ")
        dilemmas.add("Dibujar muy bien y no tener nada de imaginación o tener mucha imaginación y no saber dibujar ")
        dilemmas.add("Llevar siempre la ropa ajustada o la ropa ancha ")
        dilemmas.add("Poder escuchar música siempre que quieras sin necesidad de tecnología o poder cambiarte de ropa siempre que quieras y donde quieras ")
        dilemmas.add("No volver a pagar por comer o no volver a pagar por comprar ropa ")
        dilemmas.add("Ir siempre al cine gratis o 50% de descuento cada vez que vayas a un restaurante")
        dilemmas.add("Invasión alienígena o guerra entre todos los  paises del mundo ")
        dilemmas.add("70% de la población muere o el doble de gente en el mundo")
        dilemmas.add("Que todo el mundo te quiera por interés o que todo el mundo pase de ti ")
        dilemmas.add("Que en 20 años te den 50 millones de euros o que te den 1 millón ahora ")
        dilemmas.add("Comunicarte mentalmente con la gente o poder mover cosas con la mente ")
        dilemmas.add("Que tu internet vaya siempre muy lento o que vayas donde vayas siempre haya muchisima gente a tu alrededor ")
        dilemmas.add("Conocer tu futuro o poder cambiar algo de tu pasado ")
        dilemmas.add("Siempre llegar 1h tarde o siempre llegar 1h antes ")
        dilemmas.add("Siempre perder a todo lo que juegues o no poder jugar a nada nunca más ")
        dilemmas.add("Saber siempre cuando te están mintiendo, o que todo el mundo se crea siempre tus mentiras ")
        dilemmas.add("Siempre ducharte con agua muy fría o siempre tener que ducharte en menos de 30s ")
        dilemmas.add("Nunca más comer azúcar o que todo lo que comas sepa muy salado ")
        dilemmas.add("No volver a follar o cambiar tu orientación sexual")
        dilemmas.add("Que disparen a tu pareja en una pierna o a ti en las dos")
        dilemmas.add("Hay un boton, sí le das todos tus sueños se hacen realidad pero tienes un 10% de posibilidades de morir al instante ¿Pulsas?")
        dilemmas.add("No poder volver a hacer fotos o no poder volver a salir en ninguna ")
        dilemmas.add("Ser calvo o tener el pelo 5 metros de largo ")
        dilemmas.add("No volver a salir nunca de fiesta o no volver a ver nunca una película/serie ")
        dilemmas.add("Tener que vestir siempre de amarillo o de ir siempre con la ropa interior y los calcetines por fuera de la ropa ")
        dilemmas.add("Tener las muñecas unidas o una oreja pegada al hombro ")
        dilemmas.add("Tener que tumbarte por cada 10 metros que andes o por cada 5 minutos que estés sentado tener que levantarte ")
        dilemmas.add("Poder volar aguantando la respiración o poder respirar debajo del agua siempre que tengas los ojos cerrados ")
        dilemmas.add("Encontrar la cura del cáncer o ganar 100 millones de euros ")
        dilemmas.add("Quedarte solo de noche en el bosque o estar de día en un manicomio abandonado ")
        dilemmas.add("Ir siempre gratis en taxi a donde quieras y no tener nunca coche propio o tener el coche de tus sueños y no coger nunca el transporte público ")
        dilemmas.add("Poder viajar al futuro sin poder volver al pasado o al pasado sin poder volver al futuro ")
        dilemmas.add("Poder controlar tus propias emociones o poder controlar las del resto del mundo ")
        dilemmas.add("100 mil euros para ti o 1 millón para tú mejor amigo. (Sin poder compartir dinero)")
        dilemmas.add("Tener siempre gratis el móvil que tú quieras o pagarte tus móviles pero no quedarte nunca sin batería en ellos ")
        dilemmas.add("Hablar como Yoda o respirar como Darth Vader ")
        dilemmas.add("Controlar a los animales con la mente o controlar la tecnología con la mente ")
        dilemmas.add("Saber si hay vida más allá en el universo o saber si realmente existe Dios ")
        dilemmas.add("4 dedos en cada mano o 6 dedos en una mano ")
        dilemmas.add("Poder parar el tiempo o poder rebobinarlo ")
        dilemmas.add("Que te atormenten espíritus demoníacos todos los días por el resto de tu vida o morir justo ahora")
        dilemmas.add("Ser consciente de que vas a morir y poder asimilarlo o morir sin darte cuenta")
        dilemmas.add("No poder estar más de 2 años con tu novio/a o estar toda la vida con la misma persona")
        dilemmas.add("Tener un móvil de última generación con la pantalla rota o un móvil de hace 4 años con la pantalla perfecta")
        dilemmas.add("Comer una vez al día o dormir siempre 4 horas ")
        dilemmas.add("No tener nunca hijos o tener quintillizos de golpe ")
        dilemmas.add("Que nadie se acuerde de tu cumpleaños o que nadie te regale nada por navidad ")
        dilemmas.add("Pagar 1 euro cada vez que mires el móvil o cada vez que quieras escuchar una canción ")
        return dilemmas
    }
}