package com.mmfsin.copixuelas.queprefieres

object QuePrefieresData {

    fun getDilemmas(): List<String> {
        val dilemmas = mutableListOf<String>()
        dilemmas.add("No poder usar ningún medio de transporte nunca más %OR% perder una pierna")
        dilemmas.add("Quedarte sin familia %OR% quedarte sin amigos")
        dilemmas.add("Hacerte rico y famoso por grabar un video p*rno %OR% ganar un premio Nobel y que nadie se entere nunca")
        dilemmas.add("Ser virgen hasta los 40 %OR% no poder acostarte con nadie a partir de los 40")
        dilemmas.add("Acostarte con tu madre o con tu padre y que nadie lo sepa nunca %OR% no hacerlo y que todo el mundo piense que lo has hecho")
        dilemmas.add("Liarte con la persona de tu derecha %OR% liarte con la persona de tu izquierda")
        dilemmas.add("Matar a alguien que no conoces por diez millones de euros %OR% no matar a nadie")
        dilemmas.add("Siempre durar 5 minutos f*lland* %OR% durar 5 horas")
        dilemmas.add("Conocer la fecha de tu muerte y vivir hasta ese día %OR% no saberlo y reducir el tiempo de vida que te quede a la mitad")
        dilemmas.add("Ver el principio de la humanidad %OR% conocer cómo será el final de todo")
        dilemmas.add("Hablar muchos idiomas pero no viajar nunca %OR% solo poder hablar un idioma y viajar mucho")
        dilemmas.add("Hacer canibalismo con los cadáveres de tus amigos %OR% morir de hambre")
        dilemmas.add("No poder volver a escuchar música nunca más %OR% no poder volver a usar internet")
        dilemmas.add("No tener pulgares %OR% no tener dedos índice")
        dilemmas.add("Quedarte sin dientes %OR% quedarte sin lengua")
        dilemmas.add("Estar enamorado/a de tu pareja pero teniendo s*xo una vez al año %OR% estar en una relación tóxica con un s*xo increíble")
        dilemmas.add("Vivir eternamente %OR% morir a los 50")
        dilemmas.add("Sacrificarte para salvar a tu pareja %OR% sacrificarte para salvar a tu mejor amigo")
        dilemmas.add("Sacrificarte por salvar la humanidad %OR% no hacerlo y extinguir a los seres humanos")
        dilemmas.add("Padres eternos %OR% mascotas eternas")
        dilemmas.add("Poner los cuernos %OR% que te los pongan")
        dilemmas.add("Ser horriblemente feo/a pero muy bueno en la cama %OR% increíblemente guapo/a y malísimo/a en el s*xo")
        dilemmas.add("Perder un ojo %OR% perder una mano")
        dilemmas.add("No poder volver a ver una película %OR% no poder volver a ver una serie")
        dilemmas.add("Tener que escuchar la misma canción una vez al día el resto de tu vida %OR% solo comer verduras y frutas el resto de tu vida")
        dilemmas.add("Acabar con la todas las guerras %OR% acabar con el hambre en el mundo")
        dilemmas.add("Tener dinero infinito pero solo poder comprar cosas menores de 500€ (sin poder alquilar ni pagar a plazos) %OR% quedarte como estás")
        dilemmas.add("Usar siempre dinero en efectivo %OR% usar siempre tarjeta de credito")
        dilemmas.add("Estar muy musculado y ser horriblemente feo %OR% ser muy guapo y estar muy delgado")
        dilemmas.add("Poder tener todos los conociemientos que quieras y no poder contarle nada a nadie %OR% seguir siendo un ignorante de la vida")
        dilemmas.add("Tener una mansión %OR% tener un yate")
        dilemmas.add("¿A quién salvarías antes de la muerte? A un niño de 10 años rico y mimado %OR% a un cachorrito abandonado")
        dilemmas.add("Ser mundialmente conocido %OR% ser alguien normal")
        dilemmas.add("No volver a coger un ordenador %OR% no volver a conducir un coche")
        dilemmas.add("Matar cien cachorritos %OR% matar a un bebé")
        dilemmas.add("No tener calefacción en inviarno %OR% no tener ventilador/aire acondicionado en verano")
        dilemmas.add("Hablar muchos idiomas %OR% hablar con los animales")
        dilemmas.add("No poder saborear la comida nunca más %OR% no volver a escuchar música")
        dilemmas.add("Tener los dedos de las manos como tus piernas de largo %OR% tener tus piernas como tus dedos de la mano de largas")
        dilemmas.add("Tener la nariz donde la boca y viceversa %OR% tener un ojo encima del otro")
        dilemmas.add("Tener el cuello como una girafa %OR% tener pezuñas de cerdo en lugar de manos")
        dilemmas.add("Tener un cuerno de rinoceronte en la frente %OR% tener las manos muy peludas ")
        dilemmas.add("Hablar con tu 'yo' del pasado %OR% hablar con tu 'yo' del futuro")
        dilemmas.add("Vivir en una ciudad submarina %OR% vivir en una ciudad en las nubes")
        dilemmas.add("Tardar una hora en mear cada vez que vayas al baño %OR% no poder estar sentado más de 20 minutos nunca más")
        dilemmas.add("Andar siempre a cuatro patas %OR% andar dando saltitos")
        dilemmas.add("Ir descalzo siempre %OR% tener brazos de T-Rex")
        dilemmas.add("Tener solo dos dedos en cada mano %OR% tener una lengua de medio metro de largo")
        dilemmas.add("Hablar siempre a gritos %OR% hablar siempre susurrando")
        dilemmas.add("Que todo lo que toques se convierta en agua %OR% que todo lo que pienses se oiga en alto")
        dilemmas.add("Mearte encima siempre que tengas ganas %OR% tardar en dormirte siempre 3h")
        dilemmas.add("Cada vez que te haga algo gracia reírte histéricamente muy alto %OR% cuando estés triste ponerte a bailar incontroladamente")
        dilemmas.add("Estar arriba %OR% estar abajo")
        dilemmas.add("Que te dejen de hablar y que nunca sepas por qué %OR% dejar de hablar a alguien y no poder explicarle nunca por qué")
        dilemmas.add("Andar siempre para atrás %OR% no poder correr nunca más")
        dilemmas.add("No poder acabar una frase nunca %OR% cada vez que hables tener que mover la cabeza en círculos")
        dilemmas.add("No volver a hacer nunca nada de deporte %OR% no poder tomar alcohol nunca más")
        dilemmas.add("Dar un mal consejo a posta %OR% que te den un mal consejo de corazón")
        dilemmas.add("Comer el resto de tu vida la misma comida %OR% comer lo que quieras, pero solamente poder beber agua")
        dilemmas.add("Estar poco abrigado con mucho frío %OR% muy abrigado con mucho calor")
        dilemmas.add("Llevar siempre los calcetines mojados %OR% tener siempre toda la ropa un poco humeda")
        dilemmas.add("Tener siempre mucho sueño %OR% tener siempre mucha hambre")
        dilemmas.add("Que te duelan los ojos al cerrarlos %OR% que te duelan los dedos cada vez que los muevas")
        dilemmas.add("Poder ser invisible %OR% que todo tu cuerpo sea elástico")
        dilemmas.add("Tener s*xo con la persona de tus sueños una vez al año %OR% con alguien normal todas las veces que quieras")
        dilemmas.add("Hacer s*xo oral %OR% que te lo hagan")
        dilemmas.add("Tener que comer con cuchara lo que comes con tenedor %OR% usar siempre un cuchillo de plástico")
        dilemmas.add("Llevar siempre un pañal por encima del pantalón %OR% llevar siempre puestas unas gafas de bucear")
        dilemmas.add("No poder hablar cuando estás sentado %OR% tener que tocarte las rodillas por cada paso que des la andar")
        dilemmas.add("Ir con los brazos levantados cada vez que andes %OR% siempre que estés sentado tener las manos a la espalda")
        dilemmas.add("siempre hacer el misionero %OR% siempre hacerlo a cuatro")
        dilemmas.add("Llevar siempre un gorro de piscina puesto %OR% siempre llevar puesto un casco de bicicleta")
        dilemmas.add("No poder volver a m*sturb*rte %OR% durar como máximo 10 minutos en la cama")
        dilemmas.add("Quedarte en tu pais teniendo muy buenos amigos %OR% viajar mucho pero no conocer a nadie de verdad")
        dilemmas.add("Que la cabeza te pese el doble %OR% que todos tus movimientos sean siempre a cámara lenta")
        dilemmas.add("Que tu pareja mastique siempre con la boca abierta %OR% que tu pareja ronque mucho")
        dilemmas.add("Tener una pareja de ideología política contraria %OR% morir solo")
        dilemmas.add("Estar con tu pareja las 24h del día %OR% veros una vez al mes")
        dilemmas.add("Poder resucitar a quién tu quieras %OR% poder matar a la gente legalmente")
        dilemmas.add("Que apruebe toda la clase menos tú %OR% aprobar tú y todo el mundo suspende")
        dilemmas.add("Eternos 40 grados %OR% eternos -10 grados")
        dilemmas.add("Ser un músico mundialmente famoso y querido %OR% ser el descubridor de una teoría científica que revolucione el mundo")
        dilemmas.add("Nunca cansarte %OR% nunca enfermar")
        dilemmas.add("Ser muy bueno cocinando %OR% ser muy bueno arreglando y construyendo cosas")
        dilemmas.add("Ir 3 años a la cácel por un crimen que ha cometido tu mejor amigo/a %OR% delatarle y que él/ella vaya 10")
        dilemmas.add("Hacer algo increíble y que nadie lo aprecie nunca %OR% llevarte todo el mérito por algo que no has hecho tú")
        dilemmas.add("Poder teletransportarte pero siempre aparecer 1 semana en el futuro %OR% siempre aparecer 1 semana en el pasado")
        dilemmas.add("Medir medio metro más %OR% medir medio metro menos")
        dilemmas.add("Que te mientan por tu bien %OR% que te digan la verdad")
        dilemmas.add("Ser un músico famoso %OR% ser un actor famoso")
        dilemmas.add("No tener cuello %OR% tener los brazos la mitad de largos")
        dilemmas.add("Tener cuatro brazos %OR% poder dar saltos de 10 metros")
        dilemmas.add("No necesitar dormir %OR% no necesitar ir al baño")
        dilemmas.add("Hacer una serie mundialmente famosa %OR% hacer una película mundialmente famosa")
        dilemmas.add("Dibujar muy bien y no tener nada de imaginación %OR% tener mucha imaginación y no saber dibujar")
        dilemmas.add("Llevar siempre la ropa ajustada %OR% la ropa ancha")
        dilemmas.add("Poder escuchar música siempre que quieras sin necesidad de tecnología %OR% poder cambiarte de ropa siempre que quieras y donde quieras")
        dilemmas.add("No volver a pagar por comer %OR% no volver a pagar por comprar ropa")
        dilemmas.add("Cine y videojuegos gratis %OR% 50% de descuento cada vez que vayas a un restaurante")
        dilemmas.add("Invasión alienígena %OR% tercera guerra mundial")
        dilemmas.add("70% de la población muere %OR% doble de gente en el mundo")
        dilemmas.add("Que todo el mundo te quiera por interés %OR% que todo el mundo pase de ti")
        dilemmas.add("Que en 20 años te den 50 millones de euros %OR% que te den 1 millón ahora")
        dilemmas.add("Comunicarte mentalmente con la gente %OR% poder mover cosas con la mente")
        dilemmas.add("Que tu internet vaya siempre muy lento %OR% que estés donde estés siempre haya gente a tu alrededor")
        dilemmas.add("Conocer tu futuro %OR% poder cambiar algo de tu pasado")
        dilemmas.add("Llegar siempre 1 hora tarde %OR% llegar siempre 1 hora antes")
        dilemmas.add("Perder siempre a todo lo que juegues %OR% no poder jugar a nada nunca más")
        dilemmas.add("Saber siempre cuando te están mintiendo %OR% que todo el mundo se crea siempre tus mentiras")
        dilemmas.add("Ducharte siempre con agua muy fría %OR% siempre tener que ducharte en menos de 30 segundos")
        dilemmas.add("Nunca más comer azúcar %OR% que todo lo que comas sepa muy salado")
        dilemmas.add("Que disparen a tu pareja en una pierna %OR% que te disparen a ti en las dos")
        dilemmas.add("10% de posibilidades de morir al instante pero poder hacer real todo lo que te propongas %OR% quedarte como estás")
        dilemmas.add("No poder volver a hacer fotos %OR% no poder volver a salir en ninguna")
        dilemmas.add("Ser calvo %OR% tener el pelo 3 metros de largo")
        dilemmas.add("No volver a salir nunca de fiesta %OR% no volver a ver nunca una película/serie")
        dilemmas.add("Tener que vestir siempre de amarillo %OR% de ir siempre con la ropa interior y los calcetines por fuera de la ropa")
        dilemmas.add("Tener las muñecas unidas %OR% una oreja pegada al hombro")
        dilemmas.add("Tener que tumbarte por cada 50 metros que andes %OR% por cada 15 minutos que estés sentado tener que levantarte")
        dilemmas.add("Poder volar aguantando la respiración %OR% poder respirar debajo del agua siempre que tengas los ojos cerrados")
        dilemmas.add("Encontrar la cura del cáncer %OR% ganar 100 millones de euros")
        dilemmas.add("Quedarte solo de noche en el bosque %OR% estar de día en un manicomio abandonado")
        dilemmas.add("Ir siempre gratis en taxi a donde quieras y no tener nunca coche propio %OR% tener el coche de tus sueños y no poder coger nunca el transporte público")
        dilemmas.add("Poder viajar al futuro sin poder volver al pasado %OR% viajar al pasado sin poder volver al futuro")
        dilemmas.add("Poder controlar tus propias emociones %OR% poder controlar las emociones del resto del mundo")
        dilemmas.add("100 mil euros para ti %OR% 1 millón para tú mejor amigo. (Sin poder compartir dinero)")
        dilemmas.add("Tener siempre gratis el móvil que tú quieras %OR% pagarte tus móviles pero no quedarte nunca sin batería en ellos")
        dilemmas.add("Hablar como Yoda %OR% respirar como Darth Vader")
        dilemmas.add("Controlar a los animales con la mente %OR% controlar la tecnología con la mente")
        dilemmas.add("Saber si hay vida más allá en el universo %OR% saber si realmente existe Dios")
        dilemmas.add("4 dedos en cada mano %OR% 6 dedos en una mano")
        dilemmas.add("Poder parar el tiempo %OR% poder rebobinarlo")
        dilemmas.add("Que te atormenten espíritus demoníacos todos los días por el resto de tu vida %OR% morir justo ahora")
        dilemmas.add("Ser consciente de que vas a morir y poder asimilarlo %OR% morir sin darte cuenta")
        dilemmas.add("No poder estar más de 2 años con tu novio/a %OR% estar toda la vida con la misma persona")
        dilemmas.add("Tener un móvil de última generación con la pantalla rota %OR% un móvil de hace 4 años con la pantalla perfecta")
        dilemmas.add("Comer una vez al día %OR% dormir siempre 5 horas")
        dilemmas.add("No tener nunca hijos %OR% tener quintillizos de golpe")
        dilemmas.add("Que nadie se acuerde de tu cumpleaños %OR% que nadie te regale nada por navidad")
        dilemmas.add("Pagar 50 centimos cada vez que mires el móvil %OR% pagar 20 centimos cada vez que quieras escuchar una canción")
        return dilemmas
    }
}