package com.mmfsin.copixuelas.moneda

object MonedaData {

    fun getPreguntas(): List<String> {
        val preguntas = mutableListOf<String>()
        preguntas.add("¿Con quién grabarías un vídeo p*rno?")
        preguntas.add("¿Quién crees que es el que más tonterías dice cuando habla?")
        preguntas.add("¿Con quién no compartirías nunca piso?")
        preguntas.add("¿Quién es más probable que haya perdido la virginidad pagando?")
        preguntas.add("¿Con quién te liarías?\n(que no sea tu pareja)")
        preguntas.add("¿Quién crees que es el que menos higiene personal tiene?")
        preguntas.add("Si fuese obligatorio, ¿a quién matarias por 5 millones de euros?")
        preguntas.add("¿Quién tiene más posibilidades de acabar arruinado por problemás con las drogas?")
        preguntas.add("¿Quién es el/la más yonki?")
        preguntas.add("¿Quién crees que puede tener alguna enfermedad sexual?")
        preguntas.add("¿A quién es el que más le gusta el postureo?")
        preguntas.add("¿Quién es persona que más se masturba?")
        preguntas.add("¿Quién tiene cara de tener micropene?")
        preguntas.add("¿Quién es la persona que menos s*xo ha tenido en su vida?")
        preguntas.add("¿Quién crees que sigue siendo virgen?")
        preguntas.add("¿A quién te gustaría ver desnudo/a?")
        preguntas.add("¿Quién crees que se lo traga?")
        preguntas.add("¿Con quién no te importaría acostarte?")
        preguntas.add("¿Con quién no te importaría acostarte?")
        preguntas.add("¿Con quién no te importaría acostarte?")
        preguntas.add("¿Quién es más probable que se lie con la pareja de un amigo?")
        preguntas.add("¿Quién es más probable que tenga un hijo no deseado?")
        preguntas.add("¿Quién es el/la que peor viste?")
        preguntas.add("¿Quién crees que la tiene más grande?")
        preguntas.add("¿Quién crees que la tiene más pequeña?")
        preguntas.add("¿Quién es el/la más cansino del grupo?")
        preguntas.add("¿Quién es el más raro/maniático del grupo?")
        preguntas.add("Siendo honestos, ¿quién es el más pringado/a?")
        preguntas.add("¿Quién es más probable que tenga un gatillazo?")
        preguntas.add("¿Quién es el más pagafantas?")
        preguntas.add("¿Quién tiene cara de hacer buen s*xo oral?")
        preguntas.add("¿Quién es la persona más fea?")
        preguntas.add("¿Quién está más bueno o buena?")
        preguntas.add("¿Quién es el más sexy?")
        preguntas.add("¿Quién tiene cara de cornudo/a?")
        preguntas.add("¿Quién se ha liado con el tio/tia más feo/a que tú hayas visto?")
        preguntas.add("¿Quién es el más pesado/a de todos?")
        preguntas.add("¿Quién tiene el novio/a más feo/a?")
        preguntas.add("¿Quién podría llegar a maltratar a su mascota?")
        preguntas.add("¿Quién es la persona más infantil del grupo?")
        preguntas.add("¿Con quién no te importaría hacer un 69?")
        preguntas.add("¿Con quién no te importaría tener s*xo oral?")
        preguntas.add("¿Con quién no te importaría tener s*xo oral?")
        preguntas.add("¿Con quién no tendrías s*xo en tu vida?")
        preguntas.add("¿Quién es la persona que está más salida?")
        preguntas.add("¿Quién crees que se lía con la gente más fea?")
        preguntas.add("Si tuvieses que pelear con alguien hasta que alguno de los dos muera, ¿con quién sería?")
        preguntas.add("¿A quién dejarías que te metiese un dedo por el c*lo?")
        preguntas.add("¿Quién crees que es muy romántico/a cuando está en pareja?")
        preguntas.add("¿Quién crees que es la persona que más cambia de personalidad?")
        preguntas.add("¿Con el padre/madre de quién te acostarias?")
        preguntas.add("¿Con el hemano/hermana de quién te acostarias?")
        preguntas.add("¿Quién crees que es el que más p*rno ve?")
        preguntas.add("¿Quién tiene cara de ver alguna categoría rara de p*rno?")
        preguntas.add("¿A quién crees que le gusta el sadomasoquismo?")
        preguntas.add("¿A quién crees que le ponen c*chondo/a los pies?")
        preguntas.add("¿Quién tiene cara de tener un fetiche sexual raro?")
        preguntas.add("¿Quién podría llegar a acostarse con su hermano/a?")
        preguntas.add("¿A quién es más probable que le hagan una cobra?")
        preguntas.add("¿Quién no va a llegar a nada en la vida?")
        preguntas.add("En una pelea ¿a quién pegarían primero?")
        preguntas.add("¿Quién tiene peor gusto musical?")
        preguntas.add("¿Quién tiene cara de ser eyaculad*r precoz?")
        preguntas.add("¿Quién es más probable que no se coma un rosco de aquí a 1 año?")
        preguntas.add("¿Quién es el/la más miedica?")
        preguntas.add("¿Quién crees que grita mucho mientras f*lla?")
        preguntas.add("¿A quién crees que le puede gustar que se le meen encima?")
        preguntas.add("¿Quién tiene cara de ser multiorg*smica?")
        preguntas.add("¿Con quién crees que tendrías el mejor polvo de tu vida?")
        preguntas.add("¿Quién crees que es el más analfabeto?")
        preguntas.add("¿Quién es el más mimado/dependiente de sus padres?")
        preguntas.add("¿Quién crees que podría llegar a delatarte?")
        preguntas.add("Si todos estuvieseis en peligro de muerte, ¿a quién es al último que salvarías?")
        preguntas.add("Con la pareja o ex pareja de quién no te importaría acostarte")
        preguntas.add("¿Quien crees que es bantante bueno en el s*xo?")
        preguntas.add("¿Quien crees que es bantante bueno en el s*xo?")
        preguntas.add("¿Quién se podría liar con más personas en la misma noche?")
        preguntas.add("¿A quién no le dejarías nunca dinero?")
        preguntas.add("¿Quién es el/la más rata?")
        preguntas.add("¿Quién es más probable que vuelva con su ex?")
        preguntas.add("¿Quién es más probable que cambie su orientación sexual en el futuro?")
        preguntas.add("¿Quién sería capaz de dejar una relación por whatsapp?")
        preguntas.add("¿Quién morirá virgen?")
        preguntas.add("¿Quién lleva los tatuajes más feos?")
        preguntas.add("¿Quién es más probable que haga el ridículo en público?")
        preguntas.add("¿Quién es más probable que se líe con su primo/a?")
        preguntas.add("¿Quién es la persona que tiene más maldad?")
        preguntas.add("¿Quién tiene cara de quedarse dormido mientras llora?")
        preguntas.add("¿Quién hace un drama de todo?")
        preguntas.add("¿Quién es el más c*chondo/a suele estar?")
        preguntas.add("¿Quién se ha podido llegar a m*sturbar en un sitio público?")
        preguntas.add("¿Quién cambia de personalidad para ligar?")
        preguntas.add("¿Quién podría llegar a liarse con su mejor amigo/a de borrachera?")
        preguntas.add("¿Quién crees que llora viendo fotos de su ex?")
        preguntas.add("¿Quién es el que más presume de todo lo que hace?")
        preguntas.add("¿Quién tiene cara de ser homosexual reprimido?")
        preguntas.add("¿Quién es el/la más facha?")
        preguntas.add("¿Quién es el/la más hippie?")
        preguntas.add("¿Quién es el/la más perroflauta?")
        preguntas.add("¿A quién crees que le gusta oler la ropa interior de los demás?")
        preguntas.add("¿Quién tiene cara de que guste la zoofilia?")
        preguntas.add("¿Quién tiene cara de tener los pezones bonitos?")
        preguntas.add("¿Quién es la persona que mejores tetas tiene?")
        preguntas.add("¿Quién crees que va a morir solo?")
        preguntas.add("¿Quién es la persona que mejor culo tiene?")
        preguntas.add("¿Quién es la persona que mejor culo tiene?")
        preguntas.add("¿Quién es más probable que se tire a su a su hermano/a por dinero?")
        preguntas.add("¿Con quién crees que se puede hacer trenzas con su pelo púbico?")
        preguntas.add("¿Quién crees que tiene la garganta profunda?")
        preguntas.add("¿Quién crees que no usa el cerebro lo sufuciente?")
        preguntas.add("¿A quién crees que se le han corrido en el ojo?")
        preguntas.add("¿A quién crees que le huelen peor los genitales?")
        preguntas.add("¿Quién podría llegar a tirarse a un profesor/a para aprobar?")
        preguntas.add("¿Por quién no darías la cara en una pelea?")
        preguntas.add("¿Quién tiene pinta de masturbarse mirando fotos de su mejor amigo/a?")
        preguntas.add("¿Quién tiene pinta de masturbarse mirando fotos de su mejor ex?")
        preguntas.add("¿Quién es más propenso a poner los cuernos?")
        preguntas.add("¿A quién crees que le mide más de 20cm?")
        preguntas.add("¿Quién tiene cara de ser muy malo/a en la cama?")
        return preguntas
    }
}