package com.mmfsin.copixuelas.moneda

object MonedaData {

    fun getPreguntas(): List<String> {
        val preguntas = mutableListOf<String>()
        preguntas.add("¿Con quién grabarías un vídeo porno?")
        preguntas.add("¿Quién crees que es el que más tonterías dice cuando habla?")
        preguntas.add("¿Con quién no compartirias nunca piso?")
        preguntas.add("¿Quién es mas probable que haya perdido la virginidad pagando?")
        preguntas.add("¿Con quién te liarias?\n(que no sea tu pareja)")
        preguntas.add("¿Quién crees que es el que menos higiene personal tiene?")
        preguntas.add("Si fuese obligatorio, ¿a quién del grupo matarias por 5 millones de euros?")
        preguntas.add("¿Quién crees que debería adelgazar un poco?")
        preguntas.add("¿Quién tiene más posibilidades de acabar arruinado por problemas con las drogas?")
        preguntas.add("¿Quién es mas probable que acabe siendo un yonki?")
        preguntas.add("¿Quién crees que puede tener alguna enfermedad sexual?")
        preguntas.add("¿Quién es el más postureta del grupo?")
        preguntas.add("¿Quién crees que es el que más se masturba diariamente?")
        preguntas.add("¿Quién tiene cara de tener micropene?")
        preguntas.add("¿Quién tiene cara de follar menos?")
        preguntas.add("¿Quién tiene cara de seguir siendo virgen?")
        preguntas.add("¿A quién te gustaría ver desnudo/a?")
        preguntas.add("¿Quién crees que se lo traga?")
        preguntas.add("¿A quién te follarias?")
        preguntas.add("¿A quién te follarias?")
        preguntas.add("¿A quién te follarias?")
        preguntas.add("¿Quién es más probable que se lie con la pareja de un amigo?")
        preguntas.add("¿Quién crees que va a tener un hijo no deseado?")
        preguntas.add("¿Quién te gustaria que no estuviese aqui?")
        preguntas.add("¿Quién parece un vagabundo vistiendo?")
        preguntas.add("¿Quién crees que la tiene mas grande?")
        preguntas.add("¿Quién es el mas pesado del grupo?")
        preguntas.add("¿A quién te gustaria darle un bofetón?")
        preguntas.add("¿Quién es el más raro del grupo?")
        preguntas.add("¿Quién tiene cara de ser el mas pringao de la historia de la humanidad?")
        preguntas.add("¿A quién es mas probable que no se le levante por beber mucho alcohol?")
        preguntas.add("¿Quién es el mas pagafantas?")
        preguntas.add("¿Quién la chupa mejor?")
        preguntas.add("¿Quién tiene una cara que dan ganas de pegarle?")
        preguntas.add("¿Quién es el mas feo?")
        preguntas.add("¿Quién es el más sexy?")
        preguntas.add("¿A quién crees que le han puesto los cuernos alguna vez?")
        preguntas.add("¿Quién se ha liado con el tio/tia mas fea que hayas visto?")
        preguntas.add("¿Quién es el más pesado/a de todos?")
        preguntas.add("¿Quién tiene el novio/a más feo/a?")
        preguntas.add("¿Quién podría llegar a maltratar a su mascota?")
        preguntas.add("¿Quién es la persona más infantil del grupo?")
        preguntas.add("¿Con quién no te importaráa hacer un 69?")
        preguntas.add("¿Con quién no te importaría tener sexo oral?")
        preguntas.add("¿A quién no te tirarías en tu vida?")
        preguntas.add("¿Quién crees que intenta follar con todo lo que se mueve?")
        preguntas.add("¿Quién crees se ha masturbado con alguna fruta/verdura? (Agujero en un melón, pepino...)")
        preguntas.add("Si estuvieras en un juicio a muerte, ¿quién NO te defendería jamás?")
        preguntas.add("¿Con quién tendrías sexo anal?")
        preguntas.add("¿Quién crees que es muy romántico cuando está en pareja?")
        preguntas.add("¿Con el padre/madre de quién te acostarias?")
        preguntas.add("¿Con el hemano/hermana de quién te acostarias?")
        preguntas.add("¿Quién crees que es el que mas porno ve?")
        preguntas.add("¿Quién crees que es el que ve el porno mas raro?")
        preguntas.add("¿Quién tiene cara de practicar el sadomasoquismo?")
        preguntas.add("¿A quién crees que le ponen los pies?")
        preguntas.add("¿Quién tiene cara de tener un fetiche sexual raro?")
        preguntas.add("¿Quién es un jodido subnormal?")
        preguntas.add("¿Quién tiene cara de haberse tirado a su hermano/a?")
        preguntas.add("¿A quién es más probable que le hagan una cobra?")
        preguntas.add("¿A quién no te importaria no volverle a hablar en tu vida?")
        preguntas.add("¿Quién huele peor?")
        preguntas.add("¿A quién crees que le despidirian del trabajo por ser demasiado vago/a?")
        preguntas.add("¿A quién pegarían primero?")
        preguntas.add("¿Quién tiene peor gusto musical?")
        preguntas.add("¿Quién tiene cara de correrse a los 5 segundos?")
        preguntas.add("¿Quién tiene cara de correrse antes de bajarse los pantalones?")
        preguntas.add("¿Quién es mas propenso a tener un gatillazo?")
        preguntas.add("¿Quién es el mas miedica?")
        preguntas.add("¿Quién tiene cara de eyaculador precoz?")
        preguntas.add("¿Quién crees que grita mucho follando?")
        preguntas.add("¿Quién es el mas escandaloso/a en la cama?")
        preguntas.add("¿Quién tiene cara de que se le escape un pedo follando?")
        preguntas.add("¿A quién crees que le gusta que le meen encima?")
        preguntas.add("¿Quién tiene cara de multiorgasmica?")
        preguntas.add("¿Quién crees que ha tenido el mejor polvo de su vida?")
        preguntas.add("¿Quién crees que es el mas analfabeto?")
        preguntas.add("¿A quién le meterias un petardo por el culo?")
        preguntas.add("¿Quién es el más mimado/dependiente de sus padres?")
        preguntas.add("¿Quién crees que sería el primero en traicionarte?")
        preguntas.add("Si todos estuvieseis en peligro de muerte, ¿a quién es al último que salvarías?")
        preguntas.add("Con la pareja o ex pareja de quién no te importaría follar")
        preguntas.add("¿Quien crees que es folla muy bien?")
        preguntas.add("¿Quién se podría liar con más personas en la misma noche?")
        preguntas.add("¿A quién no le dejarías nunca mucho dinero?")
        preguntas.add("¿Quien es más probable que vuelva con su ex?")
        preguntas.add("¿Quién es mas probable que cambie su orientación sexual en el futuro?")
        preguntas.add("¿Quién sería capaz de dejar una relación por whatsapp?")
        preguntas.add("¿Quién morirá virgen?")
        preguntas.add("¿Quién lleva algún tatuaje feísimo?")
        preguntas.add("¿Quién es más probable que haga el ridículo en público?")
        preguntas.add("¿Quién es más probable que se líe con su primo/a?")
        preguntas.add("¿Quién tiene cara de acostarse todas las noches llorando?")
        preguntas.add("¿Quién hace un drama de todo?")
        preguntas.add("¿Quién es el más cachondo/a suele estar?")
        preguntas.add("¿Quien podría masturbarse en un sitio público?")
        preguntas.add("¿Quién cambia de personalidad para ligar?")
        preguntas.add("¿Quién podría llegar a liarse con su mejor amigo estando borrachos?")
        preguntas.add("¿Quién crees que llora viendo fotos de su ex?")
        preguntas.add("¿Quién es el que más presume de todo lo que hace?")
        preguntas.add("¿Quién tiene cara de ser homosexual reprimido?")
        preguntas.add("¿A quién crees que le gusta oler la ropa interior de los demás?")
        preguntas.add("¿A quien le podría gustar la zoofilia?")
        preguntas.add("¿Quién tiene cara de tener los pezones bonitos?")
        preguntas.add("¿Quién crees que va a morir solo?")
        preguntas.add("¿Quién es más probable que se tire a su a su hermano/a por dinero?")
        preguntas.add("¿Quién crees que se puede hacer trenzas con el pelo púbico?")
        preguntas.add("¿Quién crees que tiene la garganta profunda?")
        preguntas.add("¿Quién crees que no usa el cerebro lo sufuciente?")
        preguntas.add("¿Quién tiene cara de gustarle que le caguen en el pecho?")
        preguntas.add("¿A quién crees que se le han corrido en el ojo?")
        preguntas.add("¿Quién se pasa mas tiempo frente al espejo?")
        preguntas.add("¿A quién le huelen peor los genitales?")
        preguntas.add("¿Quién podría llegar a tirarse a un profesor/a para aprobar?")
        preguntas.add("¿Por quién no darías la cara en una pelea?")
        preguntas.add("¿Quién tiene pinta de masturbarse mirando fotos de su mejor amigo/a?")
        preguntas.add("¿A quién crees que le mide más de 25cm?")
        preguntas.add("¿Quién tiene cara de follar mal?")
        return preguntas
    }
}